version: '3.8'
services:
  app:
    # container_name: app # uncomment this line to give your environment a nice name to reference it by with other docker commands
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    expose:
      - "5000"
    init: true